attention_head_size: 2
categorical_groups: &id005 {}
causal_attention: true
dataset_parameters:
  add_encoder_length: true
  add_relative_time_idx: true
  add_target_scales: true
  allow_missing_timesteps: false
  categorical_encoders:
    TEAM_ID: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_: &id006
        '1610612737': 0
        '1610612738': 1
        '1610612739': 2
        '1610612740': 3
        '1610612741': 4
        '1610612742': 5
        '1610612743': 6
        '1610612744': 7
        '1610612745': 8
        '1610612746': 9
        '1610612747': 10
        '1610612748': 11
        '1610612749': 12
        '1610612750': 13
        '1610612751': 14
        '1610612752': 15
        '1610612753': 16
        '1610612754': 17
        '1610612755': 18
        '1610612756': 19
        '1610612757': 20
        '1610612758': 21
        '1610612759': 22
        '1610612760': 23
        '1610612761': 24
        '1610612762': 25
        '1610612763': 26
        '1610612764': 27
        '1610612765': 28
        '1610612766': 29
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - &id002 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 30
        - !!python/object/apply:numpy.dtype
          args:
          - U10
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 40
          - 4
          - 8
        - false
        - !!binary |
          MQAAADYAAAAxAAAAMAAAADYAAAAxAAAAMgAAADcAAAAzAAAANwAAADEAAAA2AAAAMQAAADAAAAA2
          AAAAMQAAADIAAAA3AAAAMwAAADgAAAAxAAAANgAAADEAAAAwAAAANgAAADEAAAAyAAAANwAAADMA
          AAA5AAAAMQAAADYAAAAxAAAAMAAAADYAAAAxAAAAMgAAADcAAAA0AAAAMAAAADEAAAA2AAAAMQAA
          ADAAAAA2AAAAMQAAADIAAAA3AAAANAAAADEAAAAxAAAANgAAADEAAAAwAAAANgAAADEAAAAyAAAA
          NwAAADQAAAAyAAAAMQAAADYAAAAxAAAAMAAAADYAAAAxAAAAMgAAADcAAAA0AAAAMwAAADEAAAA2
          AAAAMQAAADAAAAA2AAAAMQAAADIAAAA3AAAANAAAADQAAAAxAAAANgAAADEAAAAwAAAANgAAADEA
          AAAyAAAANwAAADQAAAA1AAAAMQAAADYAAAAxAAAAMAAAADYAAAAxAAAAMgAAADcAAAA0AAAANgAA
          ADEAAAA2AAAAMQAAADAAAAA2AAAAMQAAADIAAAA3AAAANAAAADcAAAAxAAAANgAAADEAAAAwAAAA
          NgAAADEAAAAyAAAANwAAADQAAAA4AAAAMQAAADYAAAAxAAAAMAAAADYAAAAxAAAAMgAAADcAAAA0
          AAAAOQAAADEAAAA2AAAAMQAAADAAAAA2AAAAMQAAADIAAAA3AAAANQAAADAAAAAxAAAANgAAADEA
          AAAwAAAANgAAADEAAAAyAAAANwAAADUAAAAxAAAAMQAAADYAAAAxAAAAMAAAADYAAAAxAAAAMgAA
          ADcAAAA1AAAAMgAAADEAAAA2AAAAMQAAADAAAAA2AAAAMQAAADIAAAA3AAAANQAAADMAAAAxAAAA
          NgAAADEAAAAwAAAANgAAADEAAAAyAAAANwAAADUAAAA0AAAAMQAAADYAAAAxAAAAMAAAADYAAAAx
          AAAAMgAAADcAAAA1AAAANQAAADEAAAA2AAAAMQAAADAAAAA2AAAAMQAAADIAAAA3AAAANQAAADYA
          AAAxAAAANgAAADEAAAAwAAAANgAAADEAAAAyAAAANwAAADUAAAA3AAAAMQAAADYAAAAxAAAAMAAA
          ADYAAAAxAAAAMgAAADcAAAA1AAAAOAAAADEAAAA2AAAAMQAAADAAAAA2AAAAMQAAADIAAAA3AAAA
          NQAAADkAAAAxAAAANgAAADEAAAAwAAAANgAAADEAAAAyAAAANwAAADYAAAAwAAAAMQAAADYAAAAx
          AAAAMAAAADYAAAAxAAAAMgAAADcAAAA2AAAAMQAAADEAAAA2AAAAMQAAADAAAAA2AAAAMQAAADIA
          AAA3AAAANgAAADIAAAAxAAAANgAAADEAAAAwAAAANgAAADEAAAAyAAAANwAAADYAAAAzAAAAMQAA
          ADYAAAAxAAAAMAAAADYAAAAxAAAAMgAAADcAAAA2AAAANAAAADEAAAA2AAAAMQAAADAAAAA2AAAA
          MQAAADIAAAA3AAAANgAAADUAAAAxAAAANgAAADEAAAAwAAAANgAAADEAAAAyAAAANwAAADYAAAA2
          AAAA
      warn: true
    __group_id__SEASON_ID: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          /VUAAAAAAAA=
        : 0
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          /lUAAAAAAAA=
        : 1
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          /1UAAAAAAAA=
        : 2
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AFYAAAAAAAA=
        : 3
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AVYAAAAAAAA=
        : 4
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AlYAAAAAAAA=
        : 5
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          A1YAAAAAAAA=
        : 6
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          BFYAAAAAAAA=
        : 7
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          BVYAAAAAAAA=
        : 8
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          BlYAAAAAAAA=
        : 9
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 10
        - *id001
        - false
        - !!binary |
          /VUAAAAAAAD+VQAAAAAAAP9VAAAAAAAAAFYAAAAAAAABVgAAAAAAAAJWAAAAAAAAA1YAAAAAAAAE
          VgAAAAAAAAVWAAAAAAAABlYAAAAAAAA=
      warn: true
    __group_id__TEAM_ID: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        '1610612737': 0
        '1610612738': 1
        '1610612739': 2
        '1610612740': 3
        '1610612741': 4
        '1610612742': 5
        '1610612743': 6
        '1610612744': 7
        '1610612745': 8
        '1610612746': 9
        '1610612747': 10
        '1610612748': 11
        '1610612749': 12
        '1610612750': 13
        '1610612751': 14
        '1610612752': 15
        '1610612753': 16
        '1610612754': 17
        '1610612755': 18
        '1610612756': 19
        '1610612757': 20
        '1610612758': 21
        '1610612759': 22
        '1610612760': 23
        '1610612761': 24
        '1610612762': 25
        '1610612763': 26
        '1610612764': 27
        '1610612765': 28
        '1610612766': 29
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 30
        - !!python/object/apply:numpy.dtype
          args:
          - U10
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 40
          - 4
          - 8
        - false
        - !!binary |
          MQAAADYAAAAxAAAAMAAAADYAAAAxAAAAMgAAADcAAAAzAAAANwAAADEAAAA2AAAAMQAAADAAAAA2
          AAAAMQAAADIAAAA3AAAAMwAAADgAAAAxAAAANgAAADEAAAAwAAAANgAAADEAAAAyAAAANwAAADMA
          AAA5AAAAMQAAADYAAAAxAAAAMAAAADYAAAAxAAAAMgAAADcAAAA0AAAAMAAAADEAAAA2AAAAMQAA
          ADAAAAA2AAAAMQAAADIAAAA3AAAANAAAADEAAAAxAAAANgAAADEAAAAwAAAANgAAADEAAAAyAAAA
          NwAAADQAAAAyAAAAMQAAADYAAAAxAAAAMAAAADYAAAAxAAAAMgAAADcAAAA0AAAAMwAAADEAAAA2
          AAAAMQAAADAAAAA2AAAAMQAAADIAAAA3AAAANAAAADQAAAAxAAAANgAAADEAAAAwAAAANgAAADEA
          AAAyAAAANwAAADQAAAA1AAAAMQAAADYAAAAxAAAAMAAAADYAAAAxAAAAMgAAADcAAAA0AAAANgAA
          ADEAAAA2AAAAMQAAADAAAAA2AAAAMQAAADIAAAA3AAAANAAAADcAAAAxAAAANgAAADEAAAAwAAAA
          NgAAADEAAAAyAAAANwAAADQAAAA4AAAAMQAAADYAAAAxAAAAMAAAADYAAAAxAAAAMgAAADcAAAA0
          AAAAOQAAADEAAAA2AAAAMQAAADAAAAA2AAAAMQAAADIAAAA3AAAANQAAADAAAAAxAAAANgAAADEA
          AAAwAAAANgAAADEAAAAyAAAANwAAADUAAAAxAAAAMQAAADYAAAAxAAAAMAAAADYAAAAxAAAAMgAA
          ADcAAAA1AAAAMgAAADEAAAA2AAAAMQAAADAAAAA2AAAAMQAAADIAAAA3AAAANQAAADMAAAAxAAAA
          NgAAADEAAAAwAAAANgAAADEAAAAyAAAANwAAADUAAAA0AAAAMQAAADYAAAAxAAAAMAAAADYAAAAx
          AAAAMgAAADcAAAA1AAAANQAAADEAAAA2AAAAMQAAADAAAAA2AAAAMQAAADIAAAA3AAAANQAAADYA
          AAAxAAAANgAAADEAAAAwAAAANgAAADEAAAAyAAAANwAAADUAAAA3AAAAMQAAADYAAAAxAAAAMAAA
          ADYAAAAxAAAAMgAAADcAAAA1AAAAOAAAADEAAAA2AAAAMQAAADAAAAA2AAAAMQAAADIAAAA3AAAA
          NQAAADkAAAAxAAAANgAAADEAAAAwAAAANgAAADEAAAAyAAAANwAAADYAAAAwAAAAMQAAADYAAAAx
          AAAAMAAAADYAAAAxAAAAMgAAADcAAAA2AAAAMQAAADEAAAA2AAAAMQAAADAAAAA2AAAAMQAAADIA
          AAA3AAAANgAAADIAAAAxAAAANgAAADEAAAAwAAAANgAAADEAAAAyAAAANwAAADYAAAAzAAAAMQAA
          ADYAAAAxAAAAMAAAADYAAAAxAAAAMgAAADcAAAA2AAAANAAAADEAAAA2AAAAMQAAADAAAAA2AAAA
          MQAAADIAAAA3AAAANgAAADUAAAAxAAAANgAAADEAAAAwAAAANgAAADEAAAAyAAAANwAAADYAAAA2
          AAAA
      warn: true
  constant_fill_strategy: {}
  group_ids:
  - SEASON_ID
  - TEAM_ID
  lags: {}
  max_encoder_length: 30
  max_prediction_length: 1
  min_encoder_length: 15
  min_prediction_idx: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAAAAA=
  min_prediction_length: 1
  predict_mode: false
  randomize_length: null
  scalers:
    PTS: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.2
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id004 !!python/object/apply:numpy.dtype
          args:
          - O8
          - false
          - true
          state: !!python/tuple
          - 3
          - '|'
          - null
          - null
          - null
          - -1
          - -1
          - 63
        - false
        - - PTS
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id003 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          Nj135ITMWkA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        UEYAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          W0p2IRkOKkA=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          wDxxDO82ZUA=
      with_mean: true
      with_std: true
    encoder_length: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.2
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - encoder_length
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        UEYAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    relative_time_idx: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.2
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - relative_time_idx
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        UEYAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    time_idx: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.2
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - time_idx
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAACAPUA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        UEYAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          ExC0Jm9RMUA=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          q6qqqqq+ckA=
      with_mean: true
      with_std: true
  static_categoricals: &id008
  - TEAM_ID
  static_reals: &id009
  - encoder_length
  target: WL
  target_normalizer: &id007 !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
    add_nan: false
    classes_:
      L: 0
      W: 1
    classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 2
      - !!python/object/apply:numpy.dtype
        args:
        - U1
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - 4
        - 4
        - 8
      - false
      - !!binary |
        TAAAAFcAAAA=
    warn: true
  time_idx: time_idx
  time_varying_known_categoricals: &id010
  - TEAM_ID
  time_varying_known_reals: &id011
  - time_idx
  - relative_time_idx
  time_varying_unknown_categoricals: []
  time_varying_unknown_reals:
  - PTS
  variable_groups: *id005
  weight: null
dropout: 0.1
embedding_labels:
  TEAM_ID: *id006
embedding_paddings: []
embedding_sizes:
  TEAM_ID: !!python/tuple
  - 30
  - 11
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.08
log_gradient_flow: false
log_interval: 10
log_val_interval: null
lstm_layers: 1
max_encoder_length: 30
monotone_constaints: {}
optimizer: Ranger
optimizer_params: null
output_size: 7
output_transformer: *id007
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: *id008
static_reals: *id009
time_varying_categoricals_decoder: *id010
time_varying_categoricals_encoder:
- TEAM_ID
time_varying_reals_decoder: *id011
time_varying_reals_encoder:
- time_idx
- relative_time_idx
- PTS
weight_decay: 0.0
x_categoricals:
- TEAM_ID
- TEAM_ID
x_reals:
- encoder_length
- time_idx
- relative_time_idx
- PTS
