embeddings {
  tensor_name: "PLAYER_1:02000"
  metadata_path: "02000/PLAYER_1/metadata.tsv"
  tensor_path: "02000/PLAYER_1/tensors.tsv"
}
embeddings {
  tensor_name: "PLAYER_2:02000"
  metadata_path: "02000/PLAYER_2/metadata.tsv"
  tensor_path: "02000/PLAYER_2/tensors.tsv"
}
embeddings {
  tensor_name: "PLAYER_3:02000"
  metadata_path: "02000/PLAYER_3/metadata.tsv"
  tensor_path: "02000/PLAYER_3/tensors.tsv"
}
embeddings {
  tensor_name: "PLAYER_4:02000"
  metadata_path: "02000/PLAYER_4/metadata.tsv"
  tensor_path: "02000/PLAYER_4/tensors.tsv"
}
embeddings {
  tensor_name: "PLAYER_5:02000"
  metadata_path: "02000/PLAYER_5/metadata.tsv"
  tensor_path: "02000/PLAYER_5/tensors.tsv"
}
embeddings {
  tensor_name: "OPPONENT_PLAYER_1:02000"
  metadata_path: "02000/OPPONENT_PLAYER_1/metadata.tsv"
  tensor_path: "02000/OPPONENT_PLAYER_1/tensors.tsv"
}
embeddings {
  tensor_name: "OPPONENT_PLAYER_2:02000"
  metadata_path: "02000/OPPONENT_PLAYER_2/metadata.tsv"
  tensor_path: "02000/OPPONENT_PLAYER_2/tensors.tsv"
}
embeddings {
  tensor_name: "OPPONENT_PLAYER_3:02000"
  metadata_path: "02000/OPPONENT_PLAYER_3/metadata.tsv"
  tensor_path: "02000/OPPONENT_PLAYER_3/tensors.tsv"
}
embeddings {
  tensor_name: "OPPONENT_PLAYER_4:02000"
  metadata_path: "02000/OPPONENT_PLAYER_4/metadata.tsv"
  tensor_path: "02000/OPPONENT_PLAYER_4/tensors.tsv"
}
embeddings {
  tensor_name: "OPPONENT_PLAYER_5:02000"
  metadata_path: "02000/OPPONENT_PLAYER_5/metadata.tsv"
  tensor_path: "02000/OPPONENT_PLAYER_5/tensors.tsv"
}
embeddings {
  tensor_name: "TEAM_ID:02000"
  metadata_path: "02000/TEAM_ID/metadata.tsv"
  tensor_path: "02000/TEAM_ID/tensors.tsv"
}
embeddings {
  tensor_name: "OPPONENT_ID:02000"
  metadata_path: "02000/OPPONENT_ID/metadata.tsv"
  tensor_path: "02000/OPPONENT_ID/tensors.tsv"
}
embeddings {
  tensor_name: "day_of_week:02000"
  metadata_path: "02000/day_of_week/metadata.tsv"
  tensor_path: "02000/day_of_week/tensors.tsv"
}
embeddings {
  tensor_name: "WL:02000"
  metadata_path: "02000/WL/metadata.tsv"
  tensor_path: "02000/WL/tensors.tsv"
}
